### ISSUE TITLE
Transition in <paper-calculator-panels> makes dragging the drawer very slow

### ISSUE THREAD

**Issue by esprehn** [googlearchive/paper-calculator#1]
The transition on content /content/ \* of

```
transition: -webkit-transform 0.13s linear, width 0.13s linear;
transition: transform 0.13s linear, width 0.13s linear;
```

makes dragging the drawer out extremely slow by introducing 130ms of latency into the transition changes.

**Comment by esprehn** [comment]
@abarth @frankiefu

**Comment by frankiefu** [comment]
It has a rule which supposed to remove the transition while dragging.

```
:host(.dragging) /content/ * {
  transition: none;
}
```

**Comment by frankiefu** [comment]
Fixed by https://github.com/Polymer/paper-calculator/commit/c826c4385d96759c89c3a9216551733cffbc7c02
