### ISSUE TITLE
Input has no character limit, screen size means only a certain number can be seen

### ISSUE THREAD

**Issue by shaundillon** [googlearchive/paper-calculator#4]
When typing longer sums, the characters past a certain number disappear from the edge of the screen, but are still included in the calculation.
![screen shot 2014-07-31 at 12 12 27](https://cloud.githubusercontent.com/assets/2104095/3763536/126a3222-18a4-11e4-82eb-54ce2b630261.png)

**Comment by addyosmani** [comment]
I wonder what the ideal UX should be here. If the number of entries exceed the max screen width fold to the next line? Decrease font-size?

**Comment by shaundillon** [comment]
I think decreasing font size would be less jarring, but then there'd have to be an overall limit.

**Comment by sorvell** [comment]
`paper-calculator` is a ui demo and is not meant to implement all calculator features.
