### ISSUE TITLE
Touch not enabled on iPad

### ISSUE THREAD

**Issue by naserenho** [googlearchive/paper-calculator#5]
I've been trying to test the functionality of the calculator on an iPad, but it does not read the touch button as tap rather as a mouse-click...the original polymer calculator has the touch functionality working on the iPad. Moreover this project is working fine on an Android when opening it in chrome, but not on an iPad which is really confusing, as in what part of the code is missing that could solve my issue?

**Comment by dfreedm** [comment]
Touch seems to be working fine for me on an iPad. Please reopen if this is still an issue.
