### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by alodavide** [googlearchive/paper-calculator#7]
Dear contributors,

I would like to use this code for making a calculator which will be used by biologist. I haven't seen any license in the repository, so my question is : "Can I use this code and distribute it?" 

I have already forked this repository and my code is accessible on github.

Best,
Davide

**Comment by notwaldorf** [comment]
There is a license in every code file: https://github.com/Polymer/paper-calculator/blob/master/paper-calculator-key.html#L1

**Comment by alodavide** [comment]
Well I would like to understand if it can be released undet MIT license as all polymer components.

**Comment by notwaldorf** [comment]
The full [license text](http://polymer.github.io/LICENSE.txt) mentions that: "Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer."

/cc @tjsavage

**Comment by alodavide** [comment]
I am not a real expert in licensing. I would like to fork your code and change it to handle biological data and maybe change the name of the component.

The code will be open on github.

**Comment by tjsavage** [comment]
Hey @alodavide! Definitely can use the code and distribute it. Most Polymer project code uses the BSD-style license at http://polymer.github.io/LICENSE.txt 

You're free to modify and distribute, just make sure to retain the [license headers](https://github.com/Polymer/paper-calculator/blob/master/paper-calculator-keygrid.html#L1) in all the files you redistribute.

**Comment by notwaldorf** [comment]
As a side note, this is a Polymer 0.5 application, which has been unmaintained and deprecated for a while, and I'd recommend using Polymer 1.0 in your app. Here's a bunch of migration [notes](https://www.polymer-project.org/1.0/docs/migration), which also include the polyup tool (that can help you port elements from 0.5 to 1.0)

**Comment by alodavide** [comment]
Cool :) thank you so much. I am actually thinking of rebuilding the calculator with Polymer 1.0.
I will keep you update about it.
